// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Data;

namespace MyWebApi.Migrations
{
    [DbContext(typeof(OperaContext))]
    partial class OperaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebApi.Models.Opera", b =>
                {
                    b.Property<int>("OperaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Composer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("OperaID");

                    b.ToTable("Operas");

                    b.HasData(
                        new
                        {
                            OperaID = 1,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 2,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 3,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 4,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
